# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kieren/Projects/myredis/redis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kieren/Projects/myredis/redis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kieren/Projects/myredis/redis/CMakeFiles /Users/kieren/Projects/myredis/redis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kieren/Projects/myredis/redis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redis

# Build rule for target.
redis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis
.PHONY : redis

# fast build rule for target.
redis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/build
.PHONY : redis/fast

src/adlist.o: src/adlist.c.o
.PHONY : src/adlist.o

# target to build an object file
src/adlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/adlist.c.o
.PHONY : src/adlist.c.o

src/adlist.i: src/adlist.c.i
.PHONY : src/adlist.i

# target to preprocess a source file
src/adlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/adlist.c.i
.PHONY : src/adlist.c.i

src/adlist.s: src/adlist.c.s
.PHONY : src/adlist.s

# target to generate assembly for a file
src/adlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/adlist.c.s
.PHONY : src/adlist.c.s

src/bio.o: src/bio.c.o
.PHONY : src/bio.o

# target to build an object file
src/bio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/bio.c.o
.PHONY : src/bio.c.o

src/bio.i: src/bio.c.i
.PHONY : src/bio.i

# target to preprocess a source file
src/bio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/bio.c.i
.PHONY : src/bio.c.i

src/bio.s: src/bio.c.s
.PHONY : src/bio.s

# target to generate assembly for a file
src/bio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/bio.c.s
.PHONY : src/bio.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/config.c.s
.PHONY : src/config.c.s

src/el.o: src/el.c.o
.PHONY : src/el.o

# target to build an object file
src/el.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/el.c.o
.PHONY : src/el.c.o

src/el.i: src/el.c.i
.PHONY : src/el.i

# target to preprocess a source file
src/el.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/el.c.i
.PHONY : src/el.c.i

src/el.s: src/el.c.s
.PHONY : src/el.s

# target to generate assembly for a file
src/el.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/el.c.s
.PHONY : src/el.c.s

src/rio.o: src/rio.c.o
.PHONY : src/rio.o

# target to build an object file
src/rio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/rio.c.o
.PHONY : src/rio.c.o

src/rio.i: src/rio.c.i
.PHONY : src/rio.i

# target to preprocess a source file
src/rio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/rio.c.i
.PHONY : src/rio.c.i

src/rio.s: src/rio.c.s
.PHONY : src/rio.s

# target to generate assembly for a file
src/rio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/rio.c.s
.PHONY : src/rio.c.s

src/sds.o: src/sds.c.o
.PHONY : src/sds.o

# target to build an object file
src/sds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/sds.c.o
.PHONY : src/sds.c.o

src/sds.i: src/sds.c.i
.PHONY : src/sds.i

# target to preprocess a source file
src/sds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/sds.c.i
.PHONY : src/sds.c.i

src/sds.s: src/sds.c.s
.PHONY : src/sds.s

# target to generate assembly for a file
src/sds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/sds.c.s
.PHONY : src/sds.c.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/server.c.s
.PHONY : src/server.c.s

src/syncio.o: src/syncio.c.o
.PHONY : src/syncio.o

# target to build an object file
src/syncio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/syncio.c.o
.PHONY : src/syncio.c.o

src/syncio.i: src/syncio.c.i
.PHONY : src/syncio.i

# target to preprocess a source file
src/syncio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/syncio.c.i
.PHONY : src/syncio.c.i

src/syncio.s: src/syncio.c.s
.PHONY : src/syncio.s

# target to generate assembly for a file
src/syncio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/syncio.c.s
.PHONY : src/syncio.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/varint.o: src/varint.c.o
.PHONY : src/varint.o

# target to build an object file
src/varint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/varint.c.o
.PHONY : src/varint.c.o

src/varint.i: src/varint.c.i
.PHONY : src/varint.i

# target to preprocess a source file
src/varint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/varint.c.i
.PHONY : src/varint.c.i

src/varint.s: src/varint.c.s
.PHONY : src/varint.s

# target to generate assembly for a file
src/varint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/varint.c.s
.PHONY : src/varint.c.s

src/zmalloc.o: src/zmalloc.c.o
.PHONY : src/zmalloc.o

# target to build an object file
src/zmalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/zmalloc.c.o
.PHONY : src/zmalloc.c.o

src/zmalloc.i: src/zmalloc.c.i
.PHONY : src/zmalloc.i

# target to preprocess a source file
src/zmalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/zmalloc.c.i
.PHONY : src/zmalloc.c.i

src/zmalloc.s: src/zmalloc.c.s
.PHONY : src/zmalloc.s

# target to generate assembly for a file
src/zmalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis.dir/build.make CMakeFiles/redis.dir/src/zmalloc.c.s
.PHONY : src/zmalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... redis"
	@echo "... src/adlist.o"
	@echo "... src/adlist.i"
	@echo "... src/adlist.s"
	@echo "... src/bio.o"
	@echo "... src/bio.i"
	@echo "... src/bio.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/el.o"
	@echo "... src/el.i"
	@echo "... src/el.s"
	@echo "... src/rio.o"
	@echo "... src/rio.i"
	@echo "... src/rio.s"
	@echo "... src/sds.o"
	@echo "... src/sds.i"
	@echo "... src/sds.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/syncio.o"
	@echo "... src/syncio.i"
	@echo "... src/syncio.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/varint.o"
	@echo "... src/varint.i"
	@echo "... src/varint.s"
	@echo "... src/zmalloc.o"
	@echo "... src/zmalloc.i"
	@echo "... src/zmalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

